# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 23:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='学生番号はハイフンなしの半角数字10桁で入力してください！', regex='^[0-9]{10}$')], verbose_name='学生番号')),
                ('email', models.EmailField(max_length=254, verbose_name='Eメールアドレス')),
                ('last_name', models.CharField(max_length=100, verbose_name='申請者「姓」')),
                ('first_name', models.CharField(max_length=100, verbose_name='申請者「名」')),
                ('last_name_kana', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ひらがなで入力してください！', regex='^[ぁ-んー]+$')], verbose_name='申請者「姓」（かな）')),
                ('first_name_kana', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ひらがなで入力してください！', regex='^[ぁ-んー]+$')], verbose_name='申請者「名」（かな）')),
                ('telephone', models.CharField(help_text='ハイフンは不要です', max_length=15, validators=[django.core.validators.RegexValidator(message='学生番号はハイフンなしの半角数字10桁で入力してください！', regex='^[0-9]{10}$')], verbose_name='電話番号')),
            ],
            options={
                'verbose_name': '申請者',
                'verbose_name_plural': '申請者',
            },
        ),
        migrations.CreateModel(
            name='ActivationProject',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='団体名')),
                ('name_kana', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ひらがなで入力してください！', regex='^[ぁ-んー]+$')], verbose_name='団体名（かな）')),
                ('kind', models.CharField(max_length=1, verbose_name='企画種別')),
                ('activator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='activation.Activator')),
                ('activationNo', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='学生番号はハイフンなしの半角数字10桁で入力してください！', regex='^[0-9]{10}$')], verbose_name='申請書コード')),
                ('activationPass', models.CharField(max_length=8, verbose_name='申請用パスワード')),
            ],
        ),
    ]
