# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 13:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationproject',
            options={'verbose_name': '申請団体', 'verbose_name_plural': '申請団体'},
        ),
        migrations.AlterField(
            model_name='activationproject',
            name='activator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='activation.Activator', verbose_name='申請者'),
        ),
        migrations.AlterField(
            model_name='activationproject',
            name='kind',
            field=models.CharField(choices=[('M', '模擬店企画'), ('G', 'グラウンド企画'), ('O', '屋内企画'), ('S', 'ステージ企画'), ('E', '自主制作演劇企画')], max_length=1, verbose_name='企画種別'),
        ),
        migrations.AlterField(
            model_name='activator',
            name='telephone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='電話番号はハイフンなしの半角数字で入力してください！', regex='^[0-9]+$')], verbose_name='電話番号（ハイフンなし）'),
        ),
    ]
