# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 19:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='学生番号はハイフンなしの半角数字10桁で入力してください！', regex='^[0-9]{10}$')], verbose_name='学生番号')),
                ('email', models.EmailField(max_length=254, verbose_name='Eメールアドレス')),
                ('last_name', models.CharField(max_length=100, verbose_name='姓')),
                ('first_name', models.CharField(max_length=100, verbose_name='名')),
                ('last_name_kana', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ひらがなで入力してください！', regex='^[ぁ-んー]+$')], verbose_name='姓（かな）')),
                ('first_name_kana', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ひらがなで入力してください！', regex='^[ぁ-んー]+$')], verbose_name='名（かな）')),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='電話番号はハイフンなしの半角数字で入力してください！', regex='^[0-9]+$')], verbose_name='電話番号（ハイフンなし）')),
                ('faculty', models.CharField(choices=[('総人', '総合人間学部 / 人間・環境学研究科'), ('文学', '文学部 / 文学研究科'), ('教育', '教育学部 / 教育学研究科'), ('法学', '法学部 / 法学研究科'), ('経済', '経済学部 / 経済研究科'), ('理学', '理学部 / 理学研究科'), ('工学', '工学部 / 工学研究科 / 情報学研究科'), ('農学', '農学部 / 農学研究科'), ('医学', '医学部 / 医学研究科'), ('薬学', '薬学部 / 薬学研究科'), ('他', 'その他学部 / 大学院等')], max_length=10, verbose_name='所属')),
                ('grade', models.CharField(choices=[('B1', '学部1回生'), ('B2', '学部2回生'), ('B3', '学部3回生'), ('B4', '学部4回生'), ('B5', '学部5回生'), ('B6', '学部6回生以上'), ('修士', '修士課程'), ('博士', '博士課程'), ('他', 'その他')], max_length=2, verbose_name='回生')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='団体名')),
                ('name_kana', models.CharField(max_length=100, verbose_name='団体名（かな）')),
                ('activation_no', models.CharField(help_text='半角英字で入力してください。例：「xM-001」', max_length=6, verbose_name='申請書コード')),
                ('kind', models.CharField(choices=[('模擬', '模擬店企画'), ('グラ', 'グラウンド企画'), ('屋内', '屋内企画'), ('ステ', 'ステージ企画'), ('演劇', '自主制作演劇企画')], max_length=10, verbose_name='企画種別')),
                ('activator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activator', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
