# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 14:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rawpassword',
            field=models.CharField(default='', help_text='半角英字16文字以内でお願いします', max_length=16, validators=[django.core.validators.RegexValidator(message='半角英字16文字以内でお願いします！', regex='^[a-zA-Z0-9]+$')], verbose_name='パスワード'),
            preserve_default=False,
        ),
    ]
