# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 16:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171203_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='団体名')),
                ('name_kana', models.CharField(max_length=100, verbose_name='団体名（かな）')),
                ('activation_no', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='半角英字16文字以内でお願いします！', regex='^x[A-Z]-[0-9]{3}$')], verbose_name='申請書コード')),
                ('kind', models.CharField(choices=[('模擬', '模擬店企画'), ('グラ', 'グラウンド企画'), ('屋内', '屋内企画'), ('ステ', 'ステージ企画'), ('演劇', '自主制作演劇企画')], max_length=10, verbose_name='企画種別')),
                ('activator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activator', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
