# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 21:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name_kana',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ひらがなで入力してください！', regex='^[ぁ-んー]+$')], verbose_name='名（かな）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name_kana',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ひらがなで入力してください！', regex='^[ぁ-んー]+$')], verbose_name='姓（かな）'),
        ),
    ]
